# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61sics.proto\x12\x05proto\"\x1e\n\rPUint32KeyVal\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r\"?\n\x0eSelectedItems\x12\x0e\n\x06\x61vatar\x18\x01 \x01(\r\x12\x0e\n\x06weapon\x18\x02 \x01(\r\x12\r\n\x05pet_id\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUINT32KEYVAL']._serialized_start=29
  _globals['_PUINT32KEYVAL']._serialized_end=59
  _globals['_SELECTEDITEMS']._serialized_start=61
  _globals['_SELECTEDITEMS']._serialized_end=124